data_root:
  # path of database
  DATASET_FOLDER: '/home/zjp/dataset/sequences/00/velodyne/'
  DATASET_FOLDER2: '/home/zjp/dataset/sequences/00/velodyne/'
  TRAIN_FILE: '../data/kitti/kitti00.pickle'

global:
  FEATURE_OUTPUT_DIM: 128
  RESULTS_FOLDER: "../results/"
  OUTPUT_FILE: "../results/results_01.txt"
  LOG_DIR: '../log/'
  MODEL_FILENAME: "model.ckpt"

TRAIN:
  BATCH_NUM_QUERIES: 8
  TRAIN_POSITIVES_PER_QUERY: 2
  TRAIN_NEGATIVES_PER_QUERY: 10
  DECAY_STEP: 200000
  DECAY_RATE: 0.7
  BASE_LEARNING_RATE: 0.0001
  MOMENTUM: 0.9
  OPTIMIZER: 'adam'
  MAX_EPOCH: 30

  MARGIN_1: 0.5
  MARGIN_2: 0.2

  BN_INIT_DECAY: 0.5
  BN_DECAY_DECAY_RATE: 0.5
  BN_DECAY_CLIP: 0.99
  BN_DECAY_DECAY_STEP: 200000
  RESUME: False


LOSS:
  LOSS_FUNCTION: 'quadruplet'
  LOSS_LAZY: True
  TRIPLET_USE_BEST_POSITIVES: False
  LOSS_IGNORE_ZERO_BATCH: False

EVAL:
  EVAL_BATCH_SIZE: 4
  EVAL_POSITIVES_PER_QUERY: 2
  EVAL_NEGATIVES_PER_QUERY: 10

  EVAL_DATABASE_FILE: '../data/kitti/kitti00_evaluation_database.pickle'
  EVAL_QUERY_FILE: '../data/kitti/kitti00_evaluation_query.pickle'


